version: '3.8'

services:
  python:
    build: ./server
    ports:
      - '5000:5000'
    networks:
      - network
      
  node:
    build: ./client
    ports:
      - "80:5173"
    networks:
      - network

networks:
  network:
    driver: bridge
