version: '3.8'

services:
  python:
    build: ./server
    ports:
      - '5000:5000'
    networks:
      - network
    environment:
      - API_TITLE=blast
      - API_VERSION=1
      - OPENAPI_VERSION=3.1.0
  node:
    build: ./client
    ports:
      - "80:5173"
    networks:
      - network

networks:
  network:
    driver: bridge
