POST http://localhost:5000/blast
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="query"; filename="test.fasta"
Content-Type: application/octet-stream

< ./test.fasta
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="program"

blastp
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="database"

pdbaa
------WebKitFormBoundary7MA4YWxkTrZu0gW--

POST http://localhost:5000/blast
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="query"; filename="test.fasta"
Content-Type: application/octet-stream

< ./test.fasta
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="program"

blastp
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="database"

pdbaa
------WebKitFormBoundary7MA4YWxkTrZu0gW--